/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.File;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
@Test
    public void testqoutes(){
        Quote[] quote=App.printRandomQuote();
        assertTrue(quote.length>0);

    }


    }

